#ifndef STATIONSELECTCHOICEVIEW_STATIONSELECTCHOICEVIEW_HPP_
#define STATIONSELECTCHOICEVIEW_STATIONSELECTCHOICEVIEW_HPP_


#include "PeripheralsPack.hpp"


void stationSelectChoiceView(uint8_t* modes_stack, PeripheralsPack& pack);


#endif /* STATIONSELECTCHOICEVIEW_STATIONSELECTCHOICEVIEW_HPP_ */
